import { writeFile } from "node:fs/promises";
import { Flags } from "@oclif/core";
import { BaseCommand } from "../base-command.js";
import { createApiClient } from "../lib/api.js";

export default class Export extends BaseCommand {
  static override description = "Generate a .env.example file";

  static override examples = [
    "slickenv export",
    "slickenv export --out ./docs/.env.example",
  ];

  static override flags = {
    ...BaseCommand.baseFlags,
    out: Flags.string({
      description: "Output file path",
      default: ".env.example",
    }),
  };

  async run(): Promise<void> {
    const { flags } = await this.parse(Export);

    const client = createApiClient(this.slickenvConfig.apiUrl, this.authToken);

    const snapshot = await client.query("sharing:createSnapshot" as any, {
      projectId: this.slickenvConfig.projectId,
      label: this.slickenvConfig.defaultEnvironment,
      publicOnly: false,
    }) as any;

    // Build .env.example content
    const lines: string[] = [
      `# .env.example`,
      `# Generated by SlickEnv (v${snapshot.version})`,
      `# ${snapshot.project.name} / ${snapshot.label}`,
      ``,
    ];

    for (const v of snapshot.variables) {
      // Add metadata comment
      const meta: string[] = [];
      if (v.visibility) meta.push(`@visibility=${v.visibility}`);
      if (v.required) meta.push(`@required=true`);
      if (v.type && v.type !== "string") meta.push(`@type=${v.type}`);
      if (v.example) meta.push(`@example=${v.example}`);

      if (meta.length > 0) {
        lines.push(`# ${meta.join(" ")}`);
      }

      // Public vars: show value. Private: show example or empty
      if (v.visibility === "public") {
        lines.push(`${v.key}=${v.value}`);
      } else {
        lines.push(`${v.key}=${v.example ?? ""}`);
      }
    }

    lines.push("");
    const content = lines.join("\n");

    await writeFile(flags.out, content, "utf8");
    this.success(`Exported ${snapshot.variables.length} variable${snapshot.variables.length === 1 ? "" : "s"} to ${flags.out}.`);
  }
}
