import { readFile, writeFile, access } from "node:fs/promises";
import { join } from "node:path";
import { Flags } from "@oclif/core";
import { BaseCommand } from "../../base-command.js";
import { colors, symbols, divider } from "../../lib/output.js";
import chalk from "chalk";

const SLICKENV_HEADER = "# SlickEnv — AI Tool Secret Protection";

const STANDARD_IGNORE_CONTENT = `# SlickEnv — AI Tool Secret Protection
# Generated by: slickenv ai protect

# Environment files
.env
.env.*
*.env
.env.local
.env.production
.env.staging
.env.development
.env.test
.env.backup
.env.old

# Secret/credential files
*.pem
*.key
*.p12
*.pfx
*.crt
*.cer
*credentials*
*secret*
*.secrets
secrets/
credentials/
.secrets/

# MCP configuration (may contain plaintext credentials)
.cursor/mcp.json
claude_desktop_config.json
.claude/config.json
.continue/config.json
mcp.json
mcp.*.json

# Key files
*.ssh/
id_rsa
id_ed25519
id_ecdsa
*.priv

# Backup env files
*.env.bak
*.env.orig
.env~
`;

const STANDARD_PATTERNS_COUNT = 18;

const CONTINUERC_EXCLUDE_PATTERNS = [".env", ".env.*", "*.pem", "*.key"];

interface AiTool {
  name: string;
  detectionPath: string;
  ignoreFile: string;
  alwaysGenerate?: boolean;
  specialFormat?: "continuerc";
}

const AI_TOOLS: AiTool[] = [
  { name: "Cursor", detectionPath: ".cursor", ignoreFile: ".cursorignore" },
  { name: "Claude Code", detectionPath: ".claude", ignoreFile: ".claudeignore" },
  {
    name: "GitHub Copilot",
    detectionPath: "",
    ignoreFile: ".copilotignore",
    alwaysGenerate: true,
  },
  {
    name: "Continue.dev",
    detectionPath: ".continue",
    ignoreFile: ".continuerc.json",
    specialFormat: "continuerc",
  },
  { name: "Windsurf", detectionPath: ".windsurf", ignoreFile: ".windsurfignore" },
];

async function directoryExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function hasSlickenvHeader(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, "utf8");
    return content.includes(SLICKENV_HEADER);
  } catch {
    return false;
  }
}

async function writeContinueRc(filePath: string, append: boolean): Promise<void> {
  let existing: Record<string, unknown> = {};

  if (append && (await fileExists(filePath))) {
    try {
      const raw = await readFile(filePath, "utf8");
      existing = JSON.parse(raw) as Record<string, unknown>;
    } catch {
      // Malformed JSON — overwrite with a minimal config
    }
  }

  // Merge or set fileExcludePatterns
  const currentPatterns = Array.isArray(existing.fileExcludePatterns)
    ? (existing.fileExcludePatterns as string[])
    : [];

  const merged = Array.from(new Set([...currentPatterns, ...CONTINUERC_EXCLUDE_PATTERNS]));

  const config = {
    ...existing,
    tabAutocompleteOptions: existing.tabAutocompleteOptions ?? {},
    fileExcludePatterns: merged,
  };

  await writeFile(filePath, JSON.stringify(config, null, 2) + "\n", "utf8");
}

export default class AiProtect extends BaseCommand {
  static override description = "Generate ignore files so AI coding tools do not read `.env`, MCP config, or other secret-bearing files.";

  static override examples = [
    "slickenv ai protect",
  ];

  static override flags = {
    ...BaseCommand.baseFlags,
    dir: Flags.string({
      description: "Project directory (default: current working directory)",
      default: "",
    }),
    "dry-run": Flags.boolean({
      description: "Show what would be generated without writing files",
      default: false,
    }),
    append: Flags.boolean({
      description: "Append to existing ignore files instead of overwriting",
      default: false,
    }),
  };

  protected override requiresConfig = false;
  protected override requiresAuth = false;

  async run(): Promise<void> {
    const { flags } = await this.parse(AiProtect);
    const projectDir = flags.dir || process.cwd();
    const dryRun = flags["dry-run"];
    const append = flags.append;

    this.log("");
    this.log(`  ${chalk.dim("Scanning for AI tools in this project...")}`);

    // Detect which tools are present
    const detected: Array<AiTool & { found: boolean }> = [];

    for (const tool of AI_TOOLS) {
      if (tool.alwaysGenerate) {
        this.log(
          `  ${colors.error(symbols.error)} Not found: ${chalk.bold(tool.name)} ${chalk.dim("(generating anyway as best practice)")}`
        );
        detected.push({ ...tool, found: false });
      } else {
        const exists = await directoryExists(join(projectDir, tool.detectionPath));
        if (exists) {
          this.log(
            `  ${colors.success(symbols.success)} Found: ${chalk.bold(tool.name)} ${chalk.dim(`(${tool.detectionPath}/)`)}`
          );
        }
        detected.push({ ...tool, found: exists });
      }
    }

    // Generic .aiexclude — always generate
    const genericFile = ".aiexclude";

    this.log("");

    if (dryRun) {
      this.log(`  ${chalk.dim("(dry run — no files written)")}`);
      this.log(`  Would create:`);

      for (const tool of detected) {
        if (tool.found || tool.alwaysGenerate) {
          this.log(`  ${chalk.dim(symbols.unchanged)} ${tool.ignoreFile}`);
        }
      }
      this.log(`  ${chalk.dim(symbols.unchanged)} ${genericFile}`);
      this.log("");
      return;
    }

    this.log(`  Generating AI ignore files:`);

    const toGenerate = detected.filter((t) => t.found || t.alwaysGenerate);

    for (const tool of toGenerate) {
      const filePath = join(projectDir, tool.ignoreFile);

      if (tool.specialFormat === "continuerc") {
        await writeContinueRc(filePath, append);
        this.log(
          `  ${colors.success(symbols.success)} ${tool.ignoreFile.padEnd(24)} ${chalk.dim("— exclusion patterns configured")}`
        );
      } else {
        const alreadyProtected = await hasSlickenvHeader(filePath);

        if (alreadyProtected && !append) {
          this.log(
            `  ${chalk.dim(symbols.unchanged)} ${tool.ignoreFile.padEnd(24)} ${chalk.dim("— already protected, skipped")}`
          );
          continue;
        }

        if (append && (await fileExists(filePath))) {
          const existing = await readFile(filePath, "utf8");
          if (!existing.includes(SLICKENV_HEADER)) {
            await writeFile(filePath, existing.trimEnd() + "\n\n" + STANDARD_IGNORE_CONTENT, "utf8");
            this.log(
              `  ${colors.success(symbols.success)} ${tool.ignoreFile.padEnd(24)} ${chalk.dim(`— ${STANDARD_PATTERNS_COUNT} patterns appended`)}`
            );
          } else {
            this.log(
              `  ${chalk.dim(symbols.unchanged)} ${tool.ignoreFile.padEnd(24)} ${chalk.dim("— already protected, skipped")}`
            );
          }
        } else {
          await writeFile(filePath, STANDARD_IGNORE_CONTENT, "utf8");
          this.log(
            `  ${colors.success(symbols.success)} ${tool.ignoreFile.padEnd(24)} ${chalk.dim(`— ${STANDARD_PATTERNS_COUNT} patterns added`)}`
          );
        }
      }
    }

    // Generic .aiexclude
    const genericPath = join(projectDir, genericFile);
    const genericAlreadyProtected = await hasSlickenvHeader(genericPath);

    if (genericAlreadyProtected && !append) {
      this.log(
        `  ${chalk.dim(symbols.unchanged)} ${genericFile.padEnd(24)} ${chalk.dim("— already protected, skipped")}`
      );
    } else if (append && (await fileExists(genericPath))) {
      const existing = await readFile(genericPath, "utf8");
      if (!existing.includes(SLICKENV_HEADER)) {
        await writeFile(genericPath, existing.trimEnd() + "\n\n" + STANDARD_IGNORE_CONTENT, "utf8");
        this.log(
          `  ${colors.success(symbols.success)} ${genericFile.padEnd(24)} ${chalk.dim(`— ${STANDARD_PATTERNS_COUNT} patterns appended`)}`
        );
      } else {
        this.log(
          `  ${chalk.dim(symbols.unchanged)} ${genericFile.padEnd(24)} ${chalk.dim("— already protected, skipped")}`
        );
      }
    } else {
      await writeFile(genericPath, STANDARD_IGNORE_CONTENT, "utf8");
      this.log(
        `  ${colors.success(symbols.success)} ${genericFile.padEnd(24)} ${chalk.dim(`— ${STANDARD_PATTERNS_COUNT} patterns added`)}`
      );
    }

    this.log(divider());
    this.log(
      `  ${colors.success(symbols.success)}  AI tools in this project can no longer read your secrets`
    );
    this.log("");
    this.log(
      `  Run ${colors.highlight("slickenv ai status")}  to verify protection`
    );
    this.log("");
  }
}
